# Generated by Django 3.2.3 on 2021-06-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210620_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscriver',
            new_name='subscriber',
        ),
    ]
