# Generated by Django 3.2.3 on 2021-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_subscriver_category_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(limit_choices_to={'available': True}, through='news.PostCategory', to='news.Category'),
        ),
    ]
